spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/libreria
    user: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    change-log: classpath:db/changelog/db.changelog-master.yml
